### ISSUE TITLE
配网时报错

### ISSUE THREAD

**Issue by qq547176052** [tencentyun/qcloud-iotexplorer-appdev-miniprogram-sdk-demo#4]
![image](https://user-images.githubusercontent.com/26636842/98159795-22e45e80-1f18-11eb-8969-312240797ae8.png)
![image](https://user-images.githubusercontent.com/26636842/98159829-34c60180-1f18-11eb-8552-025d17c7a371.png)

**Comment by imkero** [comment]
您好，目前小程序的真机调试功能不支持进行 UDP 通信的调试，所以真机调试运行的小程序在配网时会报错。如需调试配网，可以通过开发者工具的“预览”功能（非“真机调试”），以预览方式在手机上运行小程序进行调试。

![](https://user-images.githubusercontent.com/32296555/113129635-b44cc800-924d-11eb-9b71-e8916126f950.png)
